// app/layout.tsx

import ConfigureAmplifyClientSide from "@/components/ConfigureAmplify";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-slate-200 tetxt-slate-800 dark:bg-slate-800 dark:text-slate-200 font-sans ${inter.className}`}
      >
        <ConfigureAmplifyClientSide />
        {children}
      </body>
    </html>
  );
}
